language: java
install: ant deps
jdk:
  - openjdk7
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws.ajan
    endpoint: https://aws.ajan.s3.amazonaws.com
    region: us-west-1 
    skip_cleanup: true
    local-dir: output
    acl: public_read
    detect_encoding: true